document.writeln("<div class=\"portfolio-item-holder row\"><!-- InstanceBeginEditable name=\"EditRegion5\" -->");
document.writeln("                                        <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/pe-jaw-crusher.html\" style=\"opacity: 0;\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/pe-jaw-crusher.jpg\" alt=\"pe jaw crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/pe-jaw-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/pe-jaw-crusher.html\">pe jaw crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/pew-jaw-crusher.html\" style=\"opacity: 0;\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/pew-jaw-crusher.jpg\" alt=\"pew jaw crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/pew-jaw-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/pew-jaw-crusher.html\">pew jaw crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/hj-jaw-crusher.html\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/hJ-series-jaw-crusher.jpg\" alt=\"hj crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/hj-jaw-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/hj-jaw-crusher.html\">hj jaw crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/pf-impact-crusher.html\" style=\"opacity: 0;\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/pf-impact-crusher.jpg\" alt=\"VSI5X crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/pf-impact-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/pf-impact-crusher.html\">pf impact crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/pfw-impact-crusher.html\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/pfw-impact-crusher.jpg\" alt=\"pf impact crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/pfw-impact-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/pfw-impact-crusher.html\">pfw impact crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/cs-cone-crusher.html\" style=\"opacity: 0;\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/cs-cone-crusher.jpg\" alt=\"cs cone crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/cs-cone-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/cs-cone-crusher.html\">cs cone crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/py-cone-crusher.html\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/py-cone-crusher.jpg\" alt=\"py cone crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/py-cone-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/py-cone-crusher.html\">py cone crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/hpc-cone-crusher.html\" style=\"opacity: 0;\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/hpc-cone-crusher.jpg\" alt=\"hpc cone crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/hpc-cone-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/hpc-cone-crusher.html\">hpc cone crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/hpt-cone-crusher.html\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/hpt-cone-crusher.jpg\" alt=\"hpt cone crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/hpt-cone-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/hpt-cone-crusher.html\">hpt cone crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/hst-cone-crusher.html\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/hst-cone-crusher.jpg\" alt=\"hst crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/hst-cone-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/hst-cone-crusher.html\">hst cone crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                         <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/hammer-crusher.html\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/hammer-crusher.jpg\" alt=\"hammer crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/hammer-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            ");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/hammer-crusher.html\">hammer crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"three columns portfolio-item mb20\" style=\"height: 274px;\">");
document.writeln("                                          <div class=\"portfolio-media-wrapper gdl-image\"> <a href=\"/products/crushing/quarry-crusher.html\" style=\"opacity: 0;\"> <span class=\"portfolio-thumbnail-image-hover\"></span> <span class=\"hover-link hover-icon\"></span></a> <img src=\"/images/products/crushing-equipment/pf-impact-crusher.jpg\" alt=\"quarry crusher\"></div>");
document.writeln("                                          <div class=\"portfolio-context\">");
document.writeln("                                            <h2 class=\"portfolio-title\"> <a href=\"/products/crushing/quarry-crusher.html\">Crushing equipments</a></h2>");
document.writeln("                                            <div class=\"portfolio-tag\"> <a href=\"/products/crushing/quarry-crusher.html\">quarry crusher</a></div>");
document.writeln("                                            ");
document.writeln("                                          </div>");
document.writeln("                                        </div>");
document.writeln("                                        ");
document.writeln("                                      <!-- InstanceEndEditable --></div>");
document.writeln("                                      <div class=\"clearfix\"></div>");
document.writeln("                                      <hr>");